#MAVEN_START single-project ['clean', 'install']
#MAVEN_PLUGIN [maven-surefire-plugin:2.12.4:test (default-test) @ IT1]
[INFO] Surefire report directory: /home/adigulla/git/PyMavenRunner/it/single-project/target/surefire-reports
#START_OF_TESTS
#TEST [de.pdark.python.pmr.it1.FooTest]
#TEST_RESULT [de.pdark.python.pmr.it1.FooTest] (3, 0, 0, 0, '0.043 sec')
#ERROR Traceback (most recent call last):
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1070, in parse
    self.state(line)
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1171, in mightBeEndOfTests5
    self.emitTestSummary()
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1178, in emitTestSummary
    raise Exception(f"Can't parse final test result: {self.testSummaryLine!r}")
Exception: Can't parse final test result: 'Tests run: something else'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1202, in parse
    self.state(line)
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1304, in parseUnitTests
    self.testParser.parse(line)
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1072, in parse
    raise Exception(f'Error processing {line!r}') from ex
Exception: Error processing '[INFO]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1366, in run
    self.parser.parse(line)
  File "C:\dev\PyMavenRunner\pmr\ui.py", line 1204, in parse
    raise Exception(f'Error processing {line!r}') from ex
Exception: Error processing '[INFO]'

#MAVEN_RC != 0